export const SHOW_DATES = 'SHOW_DATES';
export const CHANGE_DATESTART = 'CHANGE_DATESTART';
export const CHANGE_FINALDATE = 'CHANGE_FINALDATE';
export const DOLLARS_VALLUE = 'DOLLARS_VALLUE';
export const AVERAGE_DOLLAR = 'AVERAGE_DOLLAR';